image: Visual Studio 2017

environment:
  matrix:
    - platform: x86
      PHP_VERSION: '7.1.6'
      VC_VERSION: '14'
      PREFER_LOWEST: 

matrix:
  fast_finish: true

init:
  - set PATH=C:\tools;C:\tools\php-%PHP_VERSION%;%PATH%

clone_depth: 50

cache:
  - C:\tools\downloads -> .appveyor.yml
  - '%LOCALAPPDATA%\Composer\files'

install:
  - if not exist C:\tools mkdir C:\tools
  - if not exist C:\tools\downloads mkdir C:\tools\downloads
  - cd /D C:\tools\downloads
  - set PHP_ZIP=php-%PHP_VERSION%-Win32-VC%VC_VERSION%-%PLATFORM%.zip
  - if not exist %PHP_ZIP% (appveyor DownloadFile http://windows.php.net/downloads/releases/archives/%PHP_ZIP% || exit 0)
  - if not exist %PHP_ZIP% (appveyor DownloadFile http://windows.php.net/downloads/releases/%PHP_ZIP% || exit 0)
  - if not exist %PHP_ZIP% appveyor DownloadFile http://windows.php.net/downloads/releases/qa/%PHP_ZIP%
  - if not exist composer.phar appveyor DownloadFile https://getcomposer.org/download/1.4.2/composer.phar
  - cd /D C:\tools
  - if not exist php-%PHP_VERSION% mkdir php-%PHP_VERSION%
  - cd /D C:\tools\php-%PHP_VERSION%
  - if not exist php-installed.txt 7z x -bd -o. -y -- ..\downloads\%PHP_ZIP% >NUL
  - if not exist php-installed.txt copy /Y php.ini-development php.ini
  - if not exist php-installed.txt echo date.timezone="UTC" >> php.ini
  - if not exist php-installed.txt echo extension_dir=ext >> php.ini
  - if not exist php-installed.txt echo extension=php_mbstring.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_intl.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_openssl >> php.ini
  - if not exist php-installed.txt echo zend.assertions=1 >> php.ini
  - if not exist php-installed.txt echo assert.exception=On >> php.ini
  - if not exist php-installed.txt type nul > php-installed.txt
  - cd /D C:\tools
  - if not exist composer.bat echo @php %%~dp0downloads\composer.phar %%* > composer.bat
  - cd /D C:\tools
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - composer self-update --no-ansi --no-interaction
  - composer install --no-progress --no-suggest --optimize-autoloader --no-ansi --no-interaction %PREFER_LOWEST%

build: off

test_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - set APPVEYOR_SAVE_CACHE_ON_ERROR=true
  - composer test

deploy: off
