language: php
sudo: false
dist: precise

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2
    - php: nightly

before_script:
  - travis_retry composer update --no-suggest --no-interaction

script:
  - composer test

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
